name: i
description: مشروع كامل فلاتر مع تنقل عربي
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  font_awesome_flutter: 10.4.0
  url_launcher: ^6.3.0







flutter:
  uses-material-design: true
  assets:
    - assets/images/
